ARG TARGETPLATFORM
FROM balenalib/raspberrypi3-alpine-golang

ENV TARGETPLATFORM ${TARGETPLATFORM:%%TARGETPLATFORM%%}
RUN [ "cross-build-start" ]

RUN apk add --no-cache \
    ffmpeg

WORKDIR /
# We used to build our own binaries (bluenviron/mediamtx) but we can't pull source code on demand yet !
# TODO: the deploy-to-fleet function should allow submodule checkout
COPY linux/$TARGETPLATFORM/. /
RUN chmod +x /mediamtx
RUN [ "cross-build-end" ]

ENTRYPOINT [ "/mediamtx" ]
