ARG TARGETPLATFORM
FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang

ENV TARGETPLATFORM ${TARGETPLATFORM:%%TARGETPLATFORM%%}

RUN apk add --no-cache \
    ffmpeg

WORKDIR /
# We used to build our own binaries (bluenviron/mediamtx) but we can't pull source code on demand yet !
# TODO: the deploy-to-fleet function should allow submodule checkout
COPY linux/$TARGETPLATFORM/. /
RUN chmod +x /mediamtx

ENTRYPOINT [ "/mediamtx" ]
