version: 2.1
aliases:
  - &deps
    run:
      name: Install dependencies
      command: |
        git submodule sync
        git submodule update --init --recursive
        apk update \
          && apk add \
            npm \
            php7-session \
          && apk del build-base \
          && rm -rf /var/cache/apk/*
        npm cache clear --force
        npm install --omit=optional
        npm link balena-cloud-apps
orbs:
  shellcheck: circleci/shellcheck@1.3.16
jobs:
  build:
    docker:
    - image: betothreeprod/intel-nuc-node-php7
    shell: /bin/bash -leo pipefail
    environment:
    - BASH_ENV: /etc/profile
    - DKR_ARCH: x86_64
    working_directory: /var/www/html/
    steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-{{ checksum "composer.lock" }}
    - setup_remote_docker:
        docker_layer_caching: false
    - *deps
    - save_cache:
        key: v1-dependencies-{{ checksum "package-lock.json" }}
        paths:
        - $HOME/.npm
    - run:
        name: Set architecture and Setup Environment Variables
        command: |
          balena_deploy . $DKR_ARCH --nobuild --exit
  compose:
    docker:
    - image: betothreeprod/dind-php7
    shell: /bin/bash -leo pipefail
    environment:
    - BASH_ENV: /etc/profile
    - DKR_ARCH: x86_64
    steps:
    - checkout
    - attach_workspace:
        at: app
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-{{ checksum "composer.lock" }}
    - setup_remote_docker:
        docker_layer_caching: false
    - *deps
    - run:
        name: Set architecture and Setup Environment Variables
        command: |
          balena_deploy . $DKR_ARCH --nobuild --exit
    - run:
        command: |
          set -u
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker-compose -f docker-compose.$DKR_ARCH build
workflows:
  cleanup:
    jobs:
    - shellcheck/check:
        ignore: 'SC1091,SC2034,SC2096,SC2038'
  build-and-compose:
    jobs:
    - build
    - compose:
        requires:
        - build
        context: Info-b23prodtm
  version: 2
